name = "intergo"

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "npx @cloudflare/next-on-pages@1"
cwd = "/frontend"
base_dir = "/frontend"
output_directory = "/.vercel/output/static"

[build.environment]
NODE_VERSION = "22.13.0"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://api.intergo.dpdns.org/"

[build_system]
version = 2
